# Makefile for Exchange App with object files in object_files/
#This was generated by an LLM for ease of use

# Compiler
CXX = g++
# Standard & warning flags
CXXFLAGS = -std=c++17 
# Optimization (change to -O2, -O3, or -Ofast if desired)
OPTFLAGS = -O2

# Output executable
TARGET = exchange_app

# Source files
SRCS = main.cpp Exchange.cpp ExecutionReport.cpp InputValidator.cpp Order.cpp OrderBook.cpp

# Directory for object files
OBJDIR = object_files

# Object files (replace .cpp with .o in object_files folder)
OBJS = $(patsubst %.cpp,$(OBJDIR)/%.o,$(SRCS))

# Default target
all: $(TARGET)

# Link object files to create executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OPTFLAGS) -o $@ $^

# Compile .cpp to .o in object_files/
$(OBJDIR)/%.o: %.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) $(OPTFLAGS) -c $< -o $@

# Ensure object_files directory exists
$(OBJDIR):
	mkdir -p $(OBJDIR)

# Clean compiled files
clean:
	rm -rf $(OBJDIR) $(TARGET)

# Run the program
run: $(TARGET)
	./$(TARGET)

